import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import Navbar from '@/components/NavBar'
import CartProvider from "@/components/CartContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode
}>) {
  return (
    <html lang="en" className="bg-white">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-black `}
      >
        
        <header className="bg-[#ef4444] text-white text-center p-4 font-bold">
          Free delivery for all orders over $50. Order your food now!
        </header>
        <CartProvider>
          <Navbar></Navbar>
          {modal}
          {children}
        </CartProvider>
        

        <footer className="flex justify-around p-2 md:p-4 text-red-400 text-2xl font-bold">
          <div className="font-bold ">MASSIMO</div>
          <div>© ALL RIGHTS RESERVED.</div>
        </footer>
      </body>
    </html>
  );
}
